DO $$
BEGIN
  ALTER TYPE "TaskActionType" ADD VALUE IF NOT EXISTS 'ACCEPT_REVIEW';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TABLE "Task"
  ADD COLUMN IF NOT EXISTS "lastReturnComment" TEXT,
  ADD COLUMN IF NOT EXISTS "lastReturnAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastReturnByUserId" TEXT;
